name: nemo
class_name: nemo.models.nemo_cls.NeMoCls

mesh_path: /misc/lmbraid21/jesslen/NeMo/data/PASCAL3D+_release1.1/CAD_single/{:s}/01.off
num_noise: 5
max_group: 512
down_sample_rate: 8

transforms:
    - class_name: nemo.datasets.pascal3d.Normalize

training:
    separate_bank: false
    distance_thr: 48
    weight_noise: 0.005
    loss_reg_weight: 0.1
    train_accumulate: 10
    T: 0.07

    optimizer:
        class_name: torch.optim.Adam
        lr: 0.0001
        weight_decay: 0.0001

    scheduler:
        class_name: torch.optim.lr_scheduler.StepLR
        step_size: 40
        gamma: 0.2

inference:
    cameras:
        class_name: pytorch3d.renderer.PerspectiveCameras
        focal_length: 3000

    raster_settings:
        class_name: pytorch3d.renderer.RasterizationSettings
        blur_radius: 0.0
        faces_per_pixel: 1
        bin_size: 0

    rasterizer:
        class_name: pytorch3d.renderer.MeshRasterizer

backbone:
    class_name: nemo.models.keypoint_representation_net.NetE2E
    net_type: resnetext
    local_size:
        - 1
        - 1
    noise_on_mask: false
    output_dimension: 128
    reduce_function: None
    pretrain: true
    n_noise_points: 5

ffnet:
    class_name: nemo.models.TODO
    net_type: resnet50
    pretrain: true

memory_bank:
    class_name: nemo.models.feature_banks_cls.NearestMemoryManager
    input_size: 128
    K: 1
    momentum: 0.96
