includes: config/pose_estimation_3d.yaml

dataset: config/datasets/ood_cv.yaml
model: config/models/resnet50_general.yaml

training:
    random_seed: 0
    batch_size: 32
    workers: 8
    total_epochs: 200
    log_interval: 5
    ckpt_interval: 10
    visualize_training_data: false

inference:
    random_seed: 0